--
-- @lc app=leetcode id=603 lang=mysql
--
-- [603] Consecutive Available Seats
--
-- https://leetcode.com/problems/consecutive-available-seats/description/
--
-- database
-- Easy (57.38%)
-- Total Accepted:    8.5K
-- Total Submissions: 14.9K
-- Testcase Example:  '{"headers":{"cinema":["seat_id","free"]},"rows":{"cinema":[[1,1],[2,0],[3,1],[4,1],[5,1]]}}'
--
-- Several friends at a cinema ticket office would like to reserve consecutive
-- available seats.
-- Can you help to query all the consecutive available seats order by the
-- seat_id using the following cinema table?
-- 
-- | seat_id | free |
-- |---------|------|
-- | 1       | 1    |
-- | 2       | 0    |
-- | 3       | 1    |
-- | 4       | 1    |
-- | 5       | 1    |
-- 
-- 
-- 
-- Your query should return the following result for the sample case
-- above.
-- 
-- 
-- 
-- 
-- | seat_id |
-- |---------|
-- | 3       |
-- | 4       |
-- | 5       |
-- 
-- Note:
-- 
-- 
-- The seat_id is an auto increment int, and free is bool ('1' means free, and
-- '0' means occupied.).
-- Consecutive available seats are more than 2(inclusive) seats consecutively
-- available.
-- 
-- 
--
# Write your MySQL query statement below

