
import java.io.FileReader;
import java.util.Arrays;

import au.com.bytecode.opencsv.CSVReader;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void readCsv() {
        try {
            CSVReader reader = new CSVReader
                (new FileReader("data.csv"),
                 ',',
                 '"',
                 0
                 );
            String [] nextLine;
            while ((nextLine = reader.readNext()) != null) {
                if (nextLine != null) {
                    // Integer xi = Integer.parseInteger(nextLine[0])
                    // Integer x  = Double.parseDouble(nextLine[2])
                    System.out.println(Arrays.toString(nextLine));
                }
            }
        } catch (Exception e){
        }
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(System.getProperty("user.dir"));
        readCsv();
    }
}
