class = com.oreilly.learningsparkexamples.mini.java.WordCount
target = learning-spark-mini-example-0.0.1.jar
arg1 = pom.xml
arg2 = sample.out
top:
	spark-submit --class $(class) target/$(target) $(arg1) $(arg2)
