/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        assertEquals("check greeting", "Hello, world4.0 9.1", Main.getGreeting());
    }
}
