--
-- @lc app=leetcode id=618 lang=mysql
--
-- [618] Students Report By Geography
--
-- https://leetcode.com/problems/students-report-by-geography/description/
--
-- database
-- Hard (41.91%)
-- Total Accepted:    2.2K
-- Total Submissions: 5.3K
-- Testcase Example:  '{"headers":{"student":["name","continent"]},"rows":{"student":[["Jane","America"],["Pascal","Europe"],["Xi","Asia"],["Jack","America"]]}}'
--
-- A U.S graduate school has students from Asia, Europe and America. The
-- students' location information are stored in table student as below.
-- 
-- 
-- 
-- | name   | continent |
-- |--------|-----------|
-- | Jack   | America   |
-- | Pascal | Europe    |
-- | Xi     | Asia      |
-- | Jane   | America   |
-- 
-- 
-- 
-- ⁠Pivot the continent column in this table so that each name is sorted
-- alphabetically and displayed underneath its corresponding continent. The
-- output headers should be America, Asia and Europe respectively. It is
-- guaranteed that the student number from America is no less than either Asia
-- or Europe.
-- 
-- 
-- For the sample input, the output is:
-- 
-- 
-- 
-- 
-- | America | Asia | Europe |
-- |---------|------|--------|
-- | Jack    | Xi   | Pascal |
-- | Jane    |      |        |
-- 
-- 
-- 
-- Follow-up: If it is unknown which continent has the most students, can you
-- write a query to generate the student report?
-- 
-- 
-- 
--
# Write your MySQL query statement below

