# pkg-config --variable=libdir x11"
new_local_repository(
    name = "usr_lib",
    path = "/usr/lib",
    build_file_content = """
cc_library(
    name = "gtest_lib",
    srcs = ["libgtest.a"],
    visibility = ["//visibility:public"],
)
"""
,
)
new_local_repository(
    name = "gnu",
    path = "/usr/lib/x86_64-linux-gnu",
    build_file_content = """
cc_library(
    name = "pthread_lib",
    srcs = ["libpthread.so"],
    visibility = ["//visibility:public"],
)
"""
,
)

new_local_repository(
    name = "glog",
    # pkg-config --variable=libdir x11"
    path = "/usr/lib/x86_64-linux-gnu",
    build_file_content = "glog.BUILD",
)
